// Robustness grid for the RVOL>=X opening-range breakout.
const { loadData, summarize } = require('./engine-sim');
const { runOrb } = require('./orb-sim');
const data = loadData();
const split = data.meta.days[Math.floor(data.D / 2)];
const pct = (ts) => ts.length ? (ts.reduce((a, t) => a + t.net / t.notional, 0) / ts.length * 100) : 0;
const months = (ts) => { const m = new Map(); for (const t of ts) { const k = t.day.slice(0, 7); m.set(k, (m.get(k) || 0) + t.netR); } const v = [...m.values()]; return `${v.filter(x => x > 0).length}/${v.length}`; };
const fmt = (ts) => { const s = summarize(ts); return s.n ? `n ${String(s.n).padStart(4)} netR ${s.netR.toFixed(3).padStart(6)} ±${s.ci.toFixed(3)} win ${String(s.win).padStart(4)}% net%/tr ${pct(ts).toFixed(3).padStart(6)}` : 'n    0'; };
const row = (label, cfg) => { const tr = runOrb(data, cfg); const y1 = tr.filter(t => t.day < split), y2 = tr.filter(t => t.day >= split); console.log(`${label.padEnd(30)} Y1 ${fmt(y1)} | Y2 ${fmt(y2)} | +months ${months(tr)}`); return tr; };
const base = { topN: 99, minRvol: 10, stopAtr: 0.2 };
console.log('-- RVOL threshold (stop 0.2 ATR)');
for (const r of [5, 7, 10, 15, 20, 30]) row(`rvol>=${r}`, { ...base, minRvol: r });
console.log('-- stop size (rvol>=10)');
for (const s of [0.1, 0.15, 0.2, 0.25, 0.35, 0.5]) row(`stop ${s} ATR`, { ...base, stopAtr: s });
row('stop = range', { ...base, stopMode: 'RANGE' });
console.log('-- exit time (rvol>=10, stop 0.2)');
for (const [lab, x] of [['11:00', 21], ['12:00', 33], ['13:30', 51], ['14:30', 63], ['15:05', 70], ['15:20', 73]]) row(`exit ${lab}`, { ...base, exitSlot: x });
console.log('-- entry deadline');
for (const [lab, x] of [['09:45', 6], ['10:15', 12], ['11:15', 24], ['15:00', 69]]) row(`entries before ${lab}`, { ...base, entryDeadlineSlot: x });
console.log('-- direction / count / liquidity / costs');
row('long only', { ...base, directions: ['LONG'] });
row('short only', { ...base, directions: ['SHORT'] });
row('top 1/day', { ...base, topN: 1 });
row('top 2/day', { ...base, topN: 2 });
row('top 3/day', { ...base, topN: 3 });
row('avg value >= 25 Cr', { ...base, minAvgValueCr: 25 });
row('avg value >= 50 Cr', { ...base, minAvgValueCr: 50 });
row('slippage x2', { ...base, slipTicks: 2, slipPct: 0.02 });
row('slippage x3', { ...base, slipTicks: 3, slipPct: 0.03 });
row('15m opening range', { ...base, orBars: 3 });
row('target 3R', { ...base, targetR: 3 });
row('target 5R', { ...base, targetR: 5 });
