import type { StrategyFormState } from "./types";
import { getLotSize } from "./types";

/** Turns the wizard's string-typed form into the JSON config object the engines and the API expect. */
export function buildStrategyConfig(form: StrategyFormState): Record<string, any> {
  const lotSize = form.lotSize || getLotSize(form.symbol, form.lotSize);
  const qty = Number(form.lots || 1) * lotSize;

  let config: any;
  if (form.type === "GAMMA_BLAST_EXPIRY") {
    config = {
      tradingMode: form.gbTradingMode === "AFTERNOON_ONLY" ? "AFTERNOON_GAMMA_ONLY" : "FULL_DAY_SCALPER",
      enableOrbMorningTrigger: form.gbEnableOrbMorningTrigger !== false,
      enableMiddayBreakout: form.gbEnableMiddayBreakout !== false,
      symbol: form.symbol.trim() === "SENSEX" ? "SENSEX" : (form.symbol.trim() === "AUTO" ? "AUTO" : "NIFTY"),
      exchange: form.symbol.trim() === "SENSEX" ? "BFO" : "NFO",
      lots: Number(form.lots || 1),
      product: form.product || "NRML",
      maxTradesPerDay: Number(form.maxTradesPerDay || 2),
      maxWinsPerDay: 1,
      autoSelectStrike: true,
      startTime: form.gbTradingMode === "AFTERNOON_ONLY" ? "13:00" : (form.gbStartTime || "09:20"),
      endTime: form.gbEndTime || "15:25",
      enableOiFilter: form.gbEnableOiFilter,
      enableVolumeSurge: form.gbEnableVolumeSurge,
      enableRatchetTrailing: form.gbEnableRatchetTrailing,
      enableHighConvictionBoost: form.gbEnableHighConvictionBoost,
      maxConvictionLots: Number(form.gbMaxConvictionLots || 3),
      enablePartialProfitBooking: form.gbEnablePartialProfitBooking,
      initialSlPct: Number(form.gbInitialSlPct || 50),
      targetRs: Number(form.targetRs || 1000),
      stopLossRs: Number(form.stopLossRs || 500),
      targetPoints: Math.round(Number(form.targetRs || 1000) / (lotSize || 20)),
      stopLossPoints: Math.round(Number(form.stopLossRs || 500) / (lotSize || 20)),
      exitExactAtTarget: !!form.exitExactAtTarget,
    };
  } else if (form.type === "NIFTY_OPTIONS_SCALPER") {
    config = {
      symbol: form.symbol.trim(),
      exchange: form.exchange,
      lots: Number(form.lots),
      qty,
      product: form.product,
      emaPeriod: 15,
      isOptionBuyingOnly: true,
      targetPoints: Number(form.dsTargetPoints || 10),
      stopLossPoints: Number(form.dsStopLossPoints || 7),
      trailCostAtPoints: Number(form.dsTrailCostAtPoints || 6),
      stopLossRs: Number(form.dsStopLossPoints || 7) * qty,
      targetRs: Number(form.dsTargetPoints || 10) * qty,
      maxTradesPerDay: Number(form.maxTradesPerDay || 2),
      maxWinsPerDay: 1,
      maxLossesPerDay: Number(form.dsMaxLossesPerDay || 2),
      enablePartialBooking: form.dsEnablePartialBooking !== false,
      partialBookingPct: Number(form.dsPartialBookingPct || 50),
      enableMiddayChopFilter: form.dsEnableMiddayChopFilter !== false,
      middayDeadZoneStart: "12:15",
      middayDeadZoneEnd: "13:15",
      enableVolumeSurge: form.dsEnableVolumeSurge !== false,
      enableTrendBiasFilter: form.dsEnableTrendBiasFilter !== false,
      enableMacroDayBias: form.dsEnableMacroDayBias !== false,
      entryCutoffTime: form.dsEntryCutoffTime || "14:15",
      timeframe: form.dsTimeframe || "5minute",
      enableOrbTrigger: false,
      enablePullbackTrigger: true,
      enableRsiFilter: false,
      enableRangeFilter: true,
      enableStagnancyExit: true,
      moneyness: "ITM",
      enableAutoHybrid: form.symbol.toUpperCase().includes("HYBRID"),
      enableDynamicSizing: form.dsEnableDynamicSizing !== false,
      maxCapital: form.dsMaxCapital ? Number(form.dsMaxCapital) : undefined,
      maxLots: form.dsMaxLots ? Number(form.dsMaxLots) : 25,
    };
  } else if (form.type === "STOCK_OPTIONS_BUYING") {
    const isAuto = form.sIsAutoStockSelect || form.symbol === "AUTO";
    config = {
      symbol: isAuto ? "AUTO" : form.symbol.trim(),
      exchange: "NSE",
      timeframe: form.sTimeframe,
      isAutoStockSelect: isAuto,
      emaPeriod: Number(form.sEmaPeriod),
      riskRewardRatio: Number(form.sRiskRewardRatio),
      maxCapital: Number(form.sMaxCapital),
      lots: Number(form.lots),
      lotSize,
      qty,
      maxTradesPerDay: Number(form.maxTradesPerDay),
      product: form.product,
      startAfterMin: Number(form.startAfterMin),
      triggerOffset: Number(form.sTriggerOffset),
      protectionBufferPct: Number(form.sProtectionBufferPct),
      directionBias: form.sDirectionBias,
      setupType: form.sSetupType,
      moneyness: form.sMoneyness,
      minRvol: Number(form.sMinRvol || 1.25),
      enableMarketTrendFilter: form.sEnableMarketTrendFilter !== false,
      enableMiddayChopFilter: form.sEnableMiddayChopFilter !== false,
      middayDeadZoneStart: "11:30",
      middayDeadZoneEnd: "13:00",
      enablePartialBooking: form.sEnablePartialBooking !== false,
      partialBookingPct: Number(form.sPartialBookingPct || 50),
      maxStagnantTimeMin: Number(form.sMaxStagnantTimeMin || 25),
      maxWinsPerDay: Number(form.sMaxWinsPerDay || 1),
      maxLossesPerDay: Number(form.sMaxLossesPerDay || 1),
      enableHtfFilter: form.sEnableHtfFilter !== false,
      enableTrailingSl: form.sEnableTrailingSl !== false,
      target1RR: Number(form.sTarget1RR || 1.5),
      target2RR: Number(form.sTarget2RR || 3.0),
      enableDynamicSizing: form.sEnableDynamicSizing !== false,
    };
  } else if (form.type === "BREAKOUT_15MIN") {
    config = {
      symbol: form.symbol.trim(),
      exchange: form.exchange,
      instrumentType: form.instrumentType,
      qty,
      lots: Number(form.lots),
      product: form.product,
      stopLossRs: Number(form.stopLossRs),
      targetRs: Number(form.targetRs),
      exitExactAtTarget: !!form.exitExactAtTarget,
      maxTradesPerDay: Number(form.maxTradesPerDay),
      enableDynamicAtr: form.b15EnableDynamicAtr,
      riskRewardRatio: Number(form.b15RiskRewardRatio),
      enableFakeoutReversal: form.b15EnableFakeoutReversal,
      enableVwapFilter: form.b15EnableVwapFilter,
      enableBreakevenTrail: form.b15EnableBreakevenTrail,
      moneyness: form.b15Moneyness,
      useStructuralCandleSl: form.b15UseStructuralCandleSl,
      maxOpeningRangePts: Number(form.b15MaxOpeningRangePts || 300),
      primeWindowEndTime: form.b15PrimeWindowEndTime || "15:00",
      enableRsiFilter: form.b15EnableRsiFilter,
      breakevenTriggerR: Number(form.b15BreakevenTriggerR || 0.7),
      enableTrapReversal: form.b15EnableTrapReversal,
      enableRetestConfirmation: form.b15EnableRetestConfirmation,
      enableCprFilter: form.b15EnableCprFilter,
      cprNarrowThresholdPct: Number(form.b15CprNarrowThresholdPct || 0.18),
      trapSlBufferPts: Number(form.b15TrapSlBufferPts || 10),
      entryTimeframe: form.b15EntryTimeframe || "3min",
      enableEmaVwapTrailing: form.b15EnableEmaVwapTrailing,
      trailingEmaPeriod: Number(form.b15TrailingEmaPeriod || 9),
      trailingVwapSource: form.b15TrailingVwapSource || "both",
      maxLossesPerDay: Number(form.b15MaxLossesPerDay || 1),
      enableMiddayChopFilter: form.b15EnableMiddayChopFilter,
      middayDeadZoneStart: form.b15MiddayDeadZoneStart || "11:45",
      middayDeadZoneEnd: form.b15MiddayDeadZoneEnd || "13:00",
      enablePartialBooking: form.b15EnablePartialBooking,
      partialBookingPct: Number(form.b15PartialBookingPct || 50),
      partialBookingR: Number(form.b15PartialBookingR || 1.8),
      enableCprSupportResistance: form.b15EnableCprSupportResistance,
      ...((form.instrumentType === 'INDEX' || form.instrumentType === 'OPTION') && {
        minPremium: Number(form.minPremium),
        maxPremium: Number(form.maxPremium),
      }),
    };
  } else {
    config = {
      symbol: form.symbol.trim(),
      exchange: form.exchange,
      instrumentType: form.instrumentType,
      emaPeriod: Number(form.emaPeriod),
      vwapSource: form.vwapSource || 'close',
      isOptionBuyingOnly: form.isOptionBuyingOnly,
      qty,
      lots: Number(form.lots),
      product: form.product,
      stopLossRs: Number(form.stopLossRs),
      targetRs: Number(form.targetRs),
      exitExactAtTarget: !!form.exitExactAtTarget,
      maxTradesPerDay: Number(form.maxTradesPerDay),
      enableProfitFloor: form.enableProfitFloor,
      profitFloorBufferRs: Number(form.profitFloorBufferRs || 100),
      ...(form.isOptionBuyingOnly && {
        minPremium: Number(form.minPremium),
        maxPremium: Number(form.maxPremium),
      }),
    };
  }

  return config;
}
