import type { StrategyFormState } from "../new/types";
import { getLotSize } from "../new/types";

/** Every field the wizard can edit, with the values a brand-new strategy starts from. */
export function createDefaultForm(): StrategyFormState {
  return {
    name: "",
    type: "",
    symbol: "NIFTY 50",
    exchange: "NSE",
    instrumentType: "INDEX",
    lots: "1",
    product: "MIS",
    stopLossRs: "500",
    targetRs: "500",
    exitExactAtTarget: false,
    maxTradesPerDay: "2",
    minPremium: "100",
    maxPremium: "300",
    enableProfitFloor: true,
    profitFloorBufferRs: "100",
    emaPeriod: "15",
    vwapSource: "close",
    isOptionBuyingOnly: true,
    emaFast: "9",
    emaSlow: "21",
    rsiPeriod: "14",
    rsiEntryMin: "45",
    rsiEntryMax: "65",
    optionLots: "1",
    targetPct: "45",
    slPct: "25",
    startAfterMin: "25",
    dsCapital: "20000",
    dsDailyTargetRs: "500",
    dsDailyMaxLossRs: "800",
    dsTargetPoints: "10",
    dsStopLossPoints: "6",
    dsMaxTradesPerDay: "2",
    dsTrailCostAtPoints: "5",
    dsMaxLossesPerDay: "2",
    dsEnablePartialBooking: false,
    dsPartialBookingPct: "50",
    dsEnableMiddayChopFilter: true,
    dsEnableVolumeSurge: false,
    dsEnableTrendBiasFilter: true,
    dsEnableMacroDayBias: false,
    dsEntryCutoffTime: "14:45",
    dsTimeframe: "5minute",
    sTimeframe: "15min",
    sEmaPeriod: "15",
    sRiskRewardRatio: "2",
    sMaxCapital: "25000",
    sTriggerOffset: "0.50",
    sProtectionBufferPct: "10",
    sDirectionBias: "BOTH",
    sSetupType: "BOTH",
    sMoneyness: "ITM",
    sIsAutoStockSelect: true,
    sMinRvol: "1.25",
    sEnableMarketTrendFilter: true,
    sEnableMiddayChopFilter: true,
    sEnablePartialBooking: true,
    sPartialBookingPct: "50",
    sMaxStagnantTimeMin: "25",
    sMaxWinsPerDay: "1",
    sMaxLossesPerDay: "1",
    sEnableHtfFilter: true,
    sEnableTrailingSl: true,
    sTarget1RR: "1.5",
    sTarget2RR: "3.0",
    sEnableDynamicSizing: true,
    b15EnableDynamicAtr: true,
    b15RiskRewardRatio: "2.0",
    b15EnableFakeoutReversal: true,
    b15EnableVwapFilter: true,
    b15EnableBreakevenTrail: true,
    b15Moneyness: "ITM",
    b15UseStructuralCandleSl: true,
    b15MaxOpeningRangePts: "300",
    b15PrimeWindowEndTime: "15:00",
    b15EnableRsiFilter: true,
    b15BreakevenTriggerR: "0.7",
    b15EnableTrapReversal: true,
    b15EnableRetestConfirmation: true,
    b15EnableCprFilter: true,
    b15CprNarrowThresholdPct: "0.18",
    b15TrapSlBufferPts: "10",
    b15EntryTimeframe: "3min",
    b15EnableEmaVwapTrailing: true,
    b15TrailingEmaPeriod: "9",
    b15TrailingVwapSource: "both",
    b15MaxLossesPerDay: "1",
    b15EnableMiddayChopFilter: true,
    b15MiddayDeadZoneStart: "11:45",
    b15MiddayDeadZoneEnd: "13:00",
    b15EnablePartialBooking: true,
    b15PartialBookingPct: "50",
    b15PartialBookingR: "1.8",
    b15EnableCprSupportResistance: true,
    gbIndex: "AUTO",
    gbTradingMode: "FULL_DAY",
    gbEnableOrbMorningTrigger: true,
    gbEnableMiddayBreakout: true,
    gbMinPremiumNifty: "8",
    gbMaxPremiumNifty: "15",
    gbMinPremiumSensex: "12",
    gbMaxPremiumSensex: "25",
    gbStartTime: "09:20",
    gbEndTime: "15:25",
    gbEnableOiFilter: true,
    gbEnableVolumeSurge: true,
    gbEnableRatchetTrailing: true,
    gbEnableHighConvictionBoost: true,
    gbMaxConvictionLots: "3",
    gbEnablePartialProfitBooking: true,
    gbInitialSlPct: "50",
    brokerAccountId: "",
    isPaperTrade: true,
  };
}

type Cfg = Record<string, any>;
const has = (v: unknown) => v !== undefined && v !== null && v !== "";
const str = (v: unknown, d: string | undefined) => (has(v) ? String(v) : d ?? "");
const bool = (v: unknown, d: boolean) => (v === undefined || v === null ? d : !!v);

interface StrategyLike {
  name: string;
  type: string;
  config?: Cfg | null;
  brokerAccountId?: string | null;
  isPaperTrade?: boolean;
}

/**
 * Inverse of buildStrategyConfig: turns a saved strategy back into the wizard's string-typed form.
 * Anything the saved config does not mention keeps the create-time default.
 */
export function strategyToForm(strategy: StrategyLike): StrategyFormState {
  const c: Cfg = strategy.config ?? {};
  const base = createDefaultForm();
  const type = strategy.type as StrategyFormState["type"];
  const lotSize = Number(c.lotSize) > 0 ? Number(c.lotSize) : getLotSize(c.symbol || "");
  const lots = has(c.lots) ? String(c.lots) : has(c.qty) && lotSize > 0 ? String(Math.max(1, Math.round(Number(c.qty) / lotSize))) : "1";
  const isGb = type === "GAMMA_BLAST_EXPIRY";
  const afternoon = c.tradingMode === "AFTERNOON_GAMMA_ONLY" || c.startTime === "13:00";

  const form: StrategyFormState = {
    ...base,
    name: strategy.name,
    type,
    symbol: str(c.symbol, isGb ? "AUTO" : base.symbol),
    exchange: str(c.exchange, c.symbol === "SENSEX" ? "BFO" : base.exchange),
    instrumentType: (c.instrumentType as StrategyFormState["instrumentType"]) || (isGb ? "OPTION" : base.instrumentType),
    lots,
    lotSize: Number(c.lotSize) > 0 ? Number(c.lotSize) : undefined,
    product: (c.product as StrategyFormState["product"]) || (isGb ? "NRML" : base.product),
    stopLossRs: str(c.stopLossRs, base.stopLossRs),
    targetRs: str(c.targetRs, isGb ? "1500" : base.targetRs),
    exitExactAtTarget: !!c.exitExactAtTarget,
    maxTradesPerDay: str(c.maxTradesPerDay, base.maxTradesPerDay),
    minPremium: str(c.minPremium, base.minPremium),
    maxPremium: str(c.maxPremium, base.maxPremium),
    enableProfitFloor: bool(c.enableProfitFloor, true),
    profitFloorBufferRs: str(c.profitFloorBufferRs, base.profitFloorBufferRs),
    emaPeriod: str(c.emaPeriod, base.emaPeriod),
    vwapSource: c.vwapSource === "hlc3" ? "hlc3" : "close",
    isOptionBuyingOnly: bool(c.isOptionBuyingOnly, true),
    startAfterMin: str(c.startAfterMin, base.startAfterMin),

    // Nifty options scalper
    dsTargetPoints: str(c.targetPoints, base.dsTargetPoints),
    dsStopLossPoints: str(c.stopLossPoints, base.dsStopLossPoints),
    dsTrailCostAtPoints: str(c.trailCostAtPoints, base.dsTrailCostAtPoints),
    dsMaxLossesPerDay: str(c.maxLossesPerDay, base.dsMaxLossesPerDay),
    dsEnablePartialBooking: bool(c.enablePartialBooking, true),
    dsPartialBookingPct: str(c.partialBookingPct, base.dsPartialBookingPct),
    dsEnableMiddayChopFilter: bool(c.enableMiddayChopFilter, true),
    dsEnableVolumeSurge: bool(c.enableVolumeSurge, true),
    dsEnableTrendBiasFilter: bool(c.enableTrendBiasFilter, true),
    dsEnableMacroDayBias: bool(c.enableMacroDayBias, true),
    dsEntryCutoffTime: str(c.entryCutoffTime, "14:15"),
    dsTimeframe: c.timeframe === "3minute" ? "3minute" : "5minute",
    dsEnableDynamicSizing: bool(c.enableDynamicSizing, true),
    dsMaxCapital: has(c.maxCapital) ? String(c.maxCapital) : "",
    dsMaxLots: has(c.maxLots) ? String(c.maxLots) : "25",

    // Stock options buying
    sTimeframe: str(c.timeframe, base.sTimeframe),
    sEmaPeriod: str(c.emaPeriod, base.sEmaPeriod),
    sRiskRewardRatio: str(c.riskRewardRatio, base.sRiskRewardRatio),
    sMaxCapital: str(c.maxCapital, base.sMaxCapital),
    sTriggerOffset: str(c.triggerOffset, base.sTriggerOffset),
    sProtectionBufferPct: str(c.protectionBufferPct, base.sProtectionBufferPct),
    sDirectionBias: c.directionBias || base.sDirectionBias,
    sSetupType: c.setupType || base.sSetupType,
    sMoneyness: c.moneyness === "ATM" ? "ATM" : "ITM",
    sIsAutoStockSelect: c.isAutoStockSelect === true || c.symbol === "AUTO",
    sMinRvol: str(c.minRvol, base.sMinRvol),
    sEnableMarketTrendFilter: bool(c.enableMarketTrendFilter, true),
    sEnableMiddayChopFilter: bool(c.enableMiddayChopFilter, true),
    sEnablePartialBooking: bool(c.enablePartialBooking, true),
    sPartialBookingPct: str(c.partialBookingPct, base.sPartialBookingPct),
    sMaxStagnantTimeMin: str(c.maxStagnantTimeMin, base.sMaxStagnantTimeMin),
    sMaxWinsPerDay: str(c.maxWinsPerDay, base.sMaxWinsPerDay),
    sMaxLossesPerDay: str(c.maxLossesPerDay, base.sMaxLossesPerDay),
    sEnableHtfFilter: bool(c.enableHtfFilter, true),
    sEnableTrailingSl: bool(c.enableTrailingSl, true),
    sTarget1RR: str(c.target1RR, base.sTarget1RR),
    sTarget2RR: str(c.target2RR, base.sTarget2RR),
    sEnableDynamicSizing: bool(c.enableDynamicSizing, true),

    // 15-min breakout
    b15EnableDynamicAtr: bool(c.enableDynamicAtr, true),
    b15RiskRewardRatio: str(c.riskRewardRatio, base.b15RiskRewardRatio),
    b15EnableFakeoutReversal: bool(c.enableFakeoutReversal, true),
    b15EnableVwapFilter: bool(c.enableVwapFilter, true),
    b15EnableBreakevenTrail: bool(c.enableBreakevenTrail, true),
    b15Moneyness: c.moneyness === "ATM" ? "ATM" : "ITM",
    b15UseStructuralCandleSl: bool(c.useStructuralCandleSl, true),
    b15MaxOpeningRangePts: str(c.maxOpeningRangePts, base.b15MaxOpeningRangePts),
    b15PrimeWindowEndTime: str(c.primeWindowEndTime, base.b15PrimeWindowEndTime),
    b15EnableRsiFilter: bool(c.enableRsiFilter, true),
    b15BreakevenTriggerR: str(c.breakevenTriggerR, base.b15BreakevenTriggerR),
    b15EnableTrapReversal: bool(c.enableTrapReversal, true),
    b15EnableRetestConfirmation: bool(c.enableRetestConfirmation, true),
    b15EnableCprFilter: bool(c.enableCprFilter, true),
    b15CprNarrowThresholdPct: str(c.cprNarrowThresholdPct, base.b15CprNarrowThresholdPct),
    b15TrapSlBufferPts: str(c.trapSlBufferPts, base.b15TrapSlBufferPts),
    b15EntryTimeframe: (c.entryTimeframe as StrategyFormState["b15EntryTimeframe"]) || base.b15EntryTimeframe,
    b15EnableEmaVwapTrailing: bool(c.enableEmaVwapTrailing, true),
    b15TrailingEmaPeriod: str(c.trailingEmaPeriod, base.b15TrailingEmaPeriod),
    b15TrailingVwapSource: (c.trailingVwapSource as StrategyFormState["b15TrailingVwapSource"]) || base.b15TrailingVwapSource,
    b15MaxLossesPerDay: str(c.maxLossesPerDay, base.b15MaxLossesPerDay),
    b15EnableMiddayChopFilter: bool(c.enableMiddayChopFilter, true),
    b15MiddayDeadZoneStart: str(c.middayDeadZoneStart, base.b15MiddayDeadZoneStart),
    b15MiddayDeadZoneEnd: str(c.middayDeadZoneEnd, base.b15MiddayDeadZoneEnd),
    b15EnablePartialBooking: bool(c.enablePartialBooking, true),
    b15PartialBookingPct: str(c.partialBookingPct, base.b15PartialBookingPct),
    b15PartialBookingR: str(c.partialBookingR, base.b15PartialBookingR),
    b15EnableCprSupportResistance: bool(c.enableCprSupportResistance, true),

    // Daily index scalper
    gbIndex: c.symbol === "NIFTY" || c.symbol === "SENSEX" ? c.symbol : "AUTO",
    gbTradingMode: afternoon ? "AFTERNOON_ONLY" : "FULL_DAY",
    gbEnableOrbMorningTrigger: bool(c.enableOrbMorningTrigger, true),
    gbEnableMiddayBreakout: bool(c.enableMiddayBreakout, true),
    gbStartTime: str(c.startTime, base.gbStartTime),
    gbEndTime: str(c.endTime, base.gbEndTime),
    gbEnableOiFilter: bool(c.enableOiFilter, true),
    gbEnableVolumeSurge: bool(c.enableVolumeSurge, true),
    gbEnableRatchetTrailing: bool(c.enableRatchetTrailing, true),
    gbEnableHighConvictionBoost: bool(c.enableHighConvictionBoost, true),
    gbMaxConvictionLots: str(c.maxConvictionLots, base.gbMaxConvictionLots),
    gbEnablePartialProfitBooking: bool(c.enablePartialProfitBooking, true),
    gbInitialSlPct: str(c.initialSlPct, base.gbInitialSlPct),

    brokerAccountId: strategy.brokerAccountId || "",
    isPaperTrade: strategy.isPaperTrade !== false,
  };

  return form;
}
