// Symbols to show in the ticker banner
export const TICKER_SYMBOLS = [
  { key: 'NSE:NIFTY 50', symbol: 'NIFTY 50', exchange: 'NSE' },
  { key: 'BSE:SENSEX', symbol: 'SENSEX', exchange: 'BSE' },
  { key: 'NSE:BANKNIFTY', symbol: 'BANKNIFTY', exchange: 'NSE' },
  { key: 'NSE:RELIANCE', symbol: 'RELIANCE', exchange: 'NSE' },
  { key: 'NSE:TCS', symbol: 'TCS', exchange: 'NSE' },
  { key: 'NSE:HDFCBANK', symbol: 'HDFCBANK', exchange: 'NSE' },
  { key: 'NSE:INFY', symbol: 'INFY', exchange: 'NSE' },
  { key: 'NSE:ICICIBANK', symbol: 'ICICIBANK', exchange: 'NSE' },
  { key: 'NSE:SBIN', symbol: 'SBIN', exchange: 'NSE' },
  { key: 'NSE:BAJFINANCE', symbol: 'BAJFINANCE', exchange: 'NSE' },
  { key: 'NSE:ITC', symbol: 'ITC', exchange: 'NSE' },
  { key: 'NSE:MARUTI', symbol: 'MARUTI', exchange: 'NSE' },
];

export const NIFTY_500_UNIVERSE = [
  '3MINDIA', 'AARTIIND', 'AAVAS', 'ABB', 'ABBOTINDIA', 'ABCAPITAL', 'ABFRL', 'ACC', 'ACE', 'ADANIENT',
  'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'ADANITRANS', 'AEGISCHEM', 'AETHER', 'AFFLE', 'AIAENG', 'AJANTPHARM', 'AKZOINDIA',
  'ALKEM', 'ALKYLAMINE', 'ALLCARGO', 'ALOKINDS', 'AMARAJABAT', 'AMBER', 'AMBUJACEM', 'ANANDRATHI', 'ANGELONE', 'ANURAS',
  'APARINDS', 'APLAPOLLO', 'APLLTD', 'APOLLOHOSP', 'APOLLOTYRE', 'APTUS', 'ARCHEAN', 'ARE&M', 'ASAHIINDIA', 'ASHOKLEY',
  'ASIANPAINT', 'ASTERDM', 'ASTRAL', 'ASTRAZEN', 'ATHERENERG', 'ATUL', 'AUBANK', 'AUROPHARMA', 'AVANTIFEED', 'AWL',
  'AXISBANK', 'BAJAJ-AUTO', 'BAJAJCON', 'BAJAJELEC', 'BAJAJFINSV', 'BAJAJHLDNG', 'BAJFINANCE', 'BALAMINES', 'BALKRISIND', 'BALMLAWRIE',
  'BALRAMCHIN', 'BANDHANBNK', 'BANKBARODA', 'BANKINDIA', 'BASF', 'BATAINDIA', 'BAYERCROP', 'BBTC', 'BDL', 'BEL',
  'BEML', 'BERGEPAINT', 'BHARATFORG', 'BHARTIARTL', 'BHEL', 'BIOCON', 'BIRLACORPN', 'BLISSGVS', 'BLUEDART', 'BLUESTARCO',
  'BOMDYEING', 'BOSCHLTD', 'BPCL', 'BRIGADE', 'BRITANNIA', 'BSE', 'BSOFT', 'CAMPUS', 'CANBK', 'CANFINHOME',
  'CAPLIPOINT', 'CARBORUNIV', 'CASTROLIND', 'CCL', 'CDSL', 'CEATLTD', 'CENTRALBK', 'CENTURYPLY', 'CENTURYTEX', 'CERA',
  'CESC', 'CGCL', 'CGPOWER', 'CHALET', 'CHAMBLFERT', 'CHEMPLASTS', 'CHENNPETRO', 'CHOLAFIN', 'CHOLAHLDNG', 'CIPLA',
  'CLEAN', 'COALINDIA', 'COCHINSHIP', 'COFORGE', 'COLPAL', 'CONCOR', 'COROMANDEL', 'CRAFTSMAN', 'CREDITACC', 'CRISIL',
  'CROMPTON', 'CUB', 'CUMMINSIND', 'CYIENT', 'DABUR', 'DALBHARAT', 'DATAPATTNS', 'DBCORP', 'DBL', 'DCMSHRIRAM',
  'DEEPAKFERT', 'DEEPAKNTR', 'DELHIVERY', 'DELTACORP', 'DEVYANI', 'DIVISLAB', 'DIXON', 'DLF', 'DMART', 'DRREDDY',
  'ECLERX', 'EDELWEISS', 'EICHERMOT', 'EIDPARRY', 'EIHOTEL', 'ELECON', 'ELGIEQUIP', 'EMAMILTD', 'EMUDHRA', 'ENDURANCE',
  'ENGINERSIN', 'EPL', 'EQUITASBNK', 'ERIS', 'ESCORTS', 'EXIDEIND', 'FDC', 'FEDERALBNK', 'FACT', 'FINCABLES',
  'FINEORG', 'FINPIPE', 'FIVESTAR', 'FLUOROCHEM', 'FORTIS', 'FSL', 'GAIL', 'GALAXYSURF', 'GICRE', 'GILLETTE',
  'GLAND', 'GLAXO', 'GLENMARK', 'GMDCLTD', 'GMRAIRPORT', 'GNFC', 'GODFRYPHLP', 'GODREJAGRO', 'GODREJCP', 'GODREJIND',
  'GODREJPROP', 'GPIL', 'GPPL', 'GRANULES', 'GRAPHITE', 'GRASIM', 'GRAVITA', 'GREAVESCOT', 'GRINDWELL', 'GSFC',
  'GSPL', 'GUJALKALI', 'GUJGASLTD', 'GULFOILLUB', 'HAL', 'HAPPSTMNDS', 'HATHWAY', 'HATSUN', 'HAVELLS', 'HBLPOWER',
  'HCLTECH', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'HEG', 'HEIDELBERG', 'HEROMOTOCO', 'HFCL', 'HGINFRA', 'HIKAL',
  'HINDALCO', 'HINDCOPPER', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'HOMEFIRST', 'HONASA', 'HONAUT', 'HSCL', 'HUDCO',
  'IBREALEST', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'ICRA', 'IDBI', 'IDEA', 'IDFC', 'IDFCFIRSTB', 'IEX',
  'IFBIND', 'IFCI', 'IGL', 'INDHOTEL', 'INDIACEM', 'INDIAGLYCO', 'INDIAMART', 'INDIANB', 'INDIGO', 'INDOCO',
  'INDUSINDBK', 'INDUSTOWER', 'INFIBEAM', 'INFY', 'INGERRAND', 'INOXINDIA', 'INOXWIND', 'INTELLECT', 'IOB', 'IOC',
  'IPCALAB', 'IRB', 'IRCON', 'IRCTC', 'IRFC', 'IREDA', 'ITC', 'ITI', 'J&KBANK', 'JBCHEPHARM',
  'JBMA', 'JINDALSAW', 'JINDALSTEL', 'JIOFIN', 'JKCEMENT', 'JKLAKSHMI', 'JKPAPER', 'JKTYRE', 'JMFINANCIL', 'JSL',
  'JSWENERGY', 'JSWINFRA', 'JSWSTEEL', 'JUBLFOOD', 'JUBLINGREA', 'JUSTDIAL', 'JYOTHYLAB', 'KABRAEXTRU', 'KAJARIACER', 'KALPATPOWR',
  'KALYANKJIL', 'KANSAINER', 'KARURVYSYA', 'KAYNES', 'KEC', 'KEI', 'KFINTECH', 'KIRLOSBROS', 'KIRLOSENG', 'KIRLPNU',
  'KNRCON', 'KOTAKBANK', 'KPIL', 'KPITTECH', 'KPRMILL', 'KRBL', 'KSB', 'KSCL', 'KTKBANK', 'L&TFH',
  'LALPATHLAB', 'LATENTVIEW', 'LAURUSLABS', 'LEMONTREE', 'LICHSGFIN', 'LICI', 'LINDEINDIA', 'LLOYDSENGG', 'LT', 'LTFOODS',
  'LTM', 'LTTS', 'LUPIN', 'LUXIND', 'M&M', 'M&MFIN', 'MAHABANK', 'MAHSEAMLES', 'MANAPPURAM', 'MANKIND',
  'MARICO', 'MARUTI', 'MASTEK', 'MAXHEALTH', 'MAZDOCK', 'MCDOWELL-N', 'MCX', 'MEDANTA', 'METROPOLIS', 'MFSL',
  'MGL', 'MHRIL', 'MINDACORP', 'MOTHERSON', 'MOTILALOFS', 'MPHASIS', 'MRF', 'MRPL', 'MSUMI', 'MUTHOOTFIN',
  'NATCOPHARM', 'NATIONALUM', 'NAUKRI', 'NAVINFLUOR', 'NBCC', 'NCC', 'NESTLEIND', 'NETWORK18', 'NEWGEN', 'NH',
  'NHPC', 'NIACL', 'NIPPOBATRY', 'NLCINDIA', 'NMDC', 'NSLNISP', 'NTPC', 'NUVAMA', 'NYKAA', 'OBEROIRLTY',
  'OFSS', 'OIL', 'OLECTRA', 'ONGC', 'PAGEIND', 'PARAS', 'PATANJALI', 'PAYTM', 'PERSISTENT', 'PETRONET',
  'PFC', 'PFIZER', 'PGHH', 'PGHL', 'PHOENIXLTD', 'PIDILITIND', 'PIIND', 'PNB', 'PNBHOUSING', 'PNCINFRA',
  'POLICYBZR', 'POLYCAB', 'POONAWALLA', 'POWERGRID', 'PRAJIND', 'PRESTIGE', 'PRINCEPIPE', 'PRSMJOHNSN', 'PTCIL', 'PVRINOX',
  'PWL', 'QUESS', 'RADICO', 'RAIN', 'RAINBOW', 'RAJESHEXPO', 'RAMCOCEM', 'RBA', 'RBLBANK', 'RCF',
  'RECLTD', 'REDINGTON', 'RELIANCE', 'RENUKA', 'RHIM', 'RITES', 'RKFORGE', 'RPOWER', 'RRKABEL', 'RUSTOMJEE',
  'RVNL', 'SAFARI', 'SAIL', 'SANOFI', 'SANSERA', 'SAPPHIRE', 'SBICARD', 'SBILIFE', 'SBIN', 'SCHAEFFLER',
  'SCHNEIDER', 'SCI', 'SHARDACROP', 'SHILPAMED', 'SHOPERSTOP', 'SHREECEM', 'SHRIRAMFIN', 'SIEMENS', 'SJVN', 'SKFINDIA',
  'SOBHA', 'SOLARINDS', 'SONACOMS', 'SONATSOFTW', 'SOUTHBANK', 'SPANDANA', 'SRF', 'STAR', 'STARHEALTH', 'STARCEMENT',
  'SUBROS', 'SUDARSCHEM', 'SUMICHEM', 'SUNDARMFIN', 'SUNDRMFAST', 'SUNPHARMA', 'SUNTECK', 'SUNTV', 'SUPRAJIT', 'SUPREMEIND',
  'SUVEN', 'SUZLON', 'SWANENERGY', 'SYMPHONY', 'SYNGENE', 'TANLA', 'TATACHEM', 'TATACOMM', 'TATACONSUM', 'TATAELXSI',
  'TATAINVEST', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL', 'TATATECH', 'TCS', 'TEAMLEASE', 'TECHM', 'TEJASNET', 'THERMAX',
  'TIINDIA', 'TIMETECHNO', 'TIMKEN', 'TITAN', 'TORNTPHARM', 'TORNTPOWER', 'TRENT', 'TRIDENT', 'TRITURBINE', 'TRIVENI',
  'TTML', 'TVSMOTOR', 'TV18BRDCST', 'UBL', 'UCOBANK', 'UFLEX', 'UJJIVANSFB', 'ULTRACEMCO', 'UNIONBANK', 'UNOMINDA',
  'UPL', 'UTIAMC', 'VAIBHAVGBL', 'VBL', 'VEDL', 'VIJAYA', 'VINATIORGA', 'VIPIND', 'VMART', 'VOLTAS',
  'VRLLOG', 'VTL', 'WABAG', 'WELCORP', 'WELENT', 'WELSPUNLIV', 'WESTLIFE', 'WHIRLPOOL', 'WIPRO', 'WOCKPHARMA',
  'YESBANK', 'ZEEL', 'ZENSARTECH', 'ZOMATO', 'ZYDUSLIFE', 'ZYDUSWELL'
];

export const FO_STOCKS_LIST = [
  // Indices
  { symbol: 'NIFTY 50', name: 'Nifty 50 Index', exchange: 'NSE', category: 'Indices', lotSize: 65 },
  { symbol: 'BANKNIFTY', name: 'Nifty Bank Index', exchange: 'NSE', category: 'Indices', lotSize: 30 },
  { symbol: 'FINNIFTY', name: 'Nifty Financial Services Index', exchange: 'NSE', category: 'Indices', lotSize: 60 },
  { symbol: 'MIDCPNIFTY', name: 'Nifty Midcap Select Index', exchange: 'NSE', category: 'Indices', lotSize: 120 },
  { symbol: 'NIFTY IT', name: 'Nifty IT Index', exchange: 'NSE', category: 'Indices', lotSize: 25 },

  // A
  { symbol: 'AARTIIND', name: 'Aarti Industries Ltd', exchange: 'NSE', category: 'Chemicals', lotSize: 1000 },
  { symbol: 'ABB', name: 'ABB India Ltd', exchange: 'NSE', category: 'Capital Goods', lotSize: 125 },
  { symbol: 'ABBOTINDIA', name: 'Abbott India Ltd', exchange: 'NSE', category: 'Pharma', lotSize: 25 },
  { symbol: 'ABCAPITAL', name: 'Aditya Birla Capital Ltd', exchange: 'NSE', category: 'Banking', lotSize: 3100 },
  { symbol: 'ABFRL', name: 'Aditya Birla Fashion & Retail', exchange: 'NSE', category: 'Consumer Goods', lotSize: 2600 },
  { symbol: 'ACC', name: 'ACC Ltd', exchange: 'NSE', category: 'Construction', lotSize: 300 },
  { symbol: 'ADANIENT', name: 'Adani Enterprises Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 300 },
  { symbol: 'ADANIPORTS', name: 'Adani Ports & SEZ Ltd', exchange: 'NSE', category: 'Infrastructure', lotSize: 400 },
  { symbol: 'ALKEM', name: 'Alkem Laboratories Ltd', exchange: 'NSE', category: 'Pharma', lotSize: 100 },
  { symbol: 'AMBUJACEM', name: 'Ambuja Cements Ltd', exchange: 'NSE', category: 'Construction', lotSize: 900 },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise', exchange: 'NSE', category: 'Pharma', lotSize: 125 },
  { symbol: 'APOLLOTYRE', name: 'Apollo Tyres Ltd', exchange: 'NSE', category: 'Auto', lotSize: 1750 },
  { symbol: 'ASHOKLEY', name: 'Ashok Leyland Ltd', exchange: 'NSE', category: 'Auto', lotSize: 5000 },
  { symbol: 'ASIANPAINT', name: 'Asian Paints Ltd', exchange: 'NSE', category: 'Consumer Goods', lotSize: 200 },
  { symbol: 'ASTRAL', name: 'Astral Ltd', exchange: 'NSE', category: 'Building Materials', lotSize: 375 },
  { symbol: 'ATUL', name: 'Atul Ltd', exchange: 'NSE', category: 'Chemicals', lotSize: 75 },
  { symbol: 'AUBANK', name: 'AU Small Finance Bank Ltd', exchange: 'NSE', category: 'Banking', lotSize: 1000 },
  { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma Ltd', exchange: 'NSE', category: 'Pharma', lotSize: 550 },
  { symbol: 'AXISBANK', name: 'Axis Bank Ltd', exchange: 'NSE', category: 'Banking', lotSize: 625 },

  // B
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto Ltd', exchange: 'NSE', category: 'Auto', lotSize: 75 },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv Ltd', exchange: 'NSE', category: 'Banking', lotSize: 500 },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance Ltd', exchange: 'NSE', category: 'Banking', lotSize: 125 },
  { symbol: 'BALKRISIND', name: 'Balkrishna Industries Ltd', exchange: 'NSE', category: 'Auto', lotSize: 300 },
  { symbol: 'BALRAMCHIN', name: 'Balrampur Chini Mills Ltd', exchange: 'NSE', category: 'Agri', lotSize: 1600 },
  { symbol: 'BANDHANBNK', name: 'Bandhan Bank Ltd', exchange: 'NSE', category: 'Banking', lotSize: 2500 },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda', exchange: 'NSE', category: 'Banking', lotSize: 2925 },
  { symbol: 'BATAINDIA', name: 'Bata India Ltd', exchange: 'NSE', category: 'Consumer Goods', lotSize: 375 },
  { symbol: 'BEL', name: 'Bharat Electronics Ltd', exchange: 'NSE', category: 'Defence', lotSize: 2850 },
  { symbol: 'BERGEPAINT', name: 'Berger Paints India Ltd', exchange: 'NSE', category: 'Consumer Goods', lotSize: 1100 },
  { symbol: 'BHARATFORG', name: 'Bharat Forge Ltd', exchange: 'NSE', category: 'Capital Goods', lotSize: 500 },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel Ltd', exchange: 'NSE', category: 'Telecommunication', lotSize: 475 },
  { symbol: 'BHEL', name: 'Bharat Heavy Electricals Ltd', exchange: 'NSE', category: 'Capital Goods', lotSize: 2625 },
  { symbol: 'BIOCON', name: 'Biocon Ltd', exchange: 'NSE', category: 'Pharma', lotSize: 2500 },
  { symbol: 'BOSCHLTD', name: 'Bosch Ltd', exchange: 'NSE', category: 'Auto', lotSize: 25 },
  { symbol: 'BPCL', name: 'Bharat Petroleum Corp Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 1975 },
  { symbol: 'BRITANNIA', name: 'Britannia Industries Ltd', exchange: 'NSE', category: 'FMCG', lotSize: 200 },
  { symbol: 'BSOFT', name: 'Birlasoft Ltd', exchange: 'NSE', category: 'IT', lotSize: 1000 },

  // C
  { symbol: 'CANBK', name: 'Canara Bank', exchange: 'NSE', category: 'Banking', lotSize: 6750 },
  { symbol: 'CANFINHOME', name: 'Can Fin Homes Ltd', exchange: 'NSE', category: 'Banking', lotSize: 650 },
  { symbol: 'CHAMBLFERT', name: 'Chambal Fertilisers & Chem', exchange: 'NSE', category: 'Chemicals', lotSize: 1500 },
  { symbol: 'CHOLAFIN', name: 'Cholamandalam Investment', exchange: 'NSE', category: 'Banking', lotSize: 625 },
  { symbol: 'CIPLA', name: 'Cipla Ltd', exchange: 'NSE', category: 'Pharma', lotSize: 650 },
  { symbol: 'COALINDIA', name: 'Coal India Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 2100 },
  { symbol: 'COFORGE', name: 'Coforge Ltd', exchange: 'NSE', category: 'IT', lotSize: 150 },
  { symbol: 'COLPAL', name: 'Colgate-Palmolive India Ltd', exchange: 'NSE', category: 'FMCG', lotSize: 350 },
  { symbol: 'CONCOR', name: 'Container Corp of India', exchange: 'NSE', category: 'Infrastructure', lotSize: 1000 },
  { symbol: 'COROMANDEL', name: 'Coromandel International', exchange: 'NSE', category: 'Chemicals', lotSize: 700 },
  { symbol: 'CROMPTON', name: 'Crompton Greaves Consumer', exchange: 'NSE', category: 'Consumer Goods', lotSize: 1800 },
  { symbol: 'CUMMINSIND', name: 'Cummins India Ltd', exchange: 'NSE', category: 'Capital Goods', lotSize: 300 },

  // D
  { symbol: 'DABUR', name: 'Dabur India Ltd', exchange: 'NSE', category: 'FMCG', lotSize: 1250 },
  { symbol: 'DALBHARAT', name: 'Dalmia Bharat Ltd', exchange: 'NSE', category: 'Construction', lotSize: 250 },
  { symbol: 'DEEPAKNTR', name: 'Deepak Nitrite Ltd', exchange: 'NSE', category: 'Chemicals', lotSize: 300 },
  { symbol: 'DIVISLAB', name: 'Divis Laboratories Ltd', exchange: 'NSE', category: 'Pharma', lotSize: 150 },
  { symbol: 'DIXON', name: 'Dixon Technologies Ltd', exchange: 'NSE', category: 'Consumer Goods', lotSize: 100 },
  { symbol: 'DLF', name: 'DLF Ltd', exchange: 'NSE', category: 'Real Estate', lotSize: 825 },
  { symbol: 'DRREDDY', name: 'Dr Reddys Laboratories Ltd', exchange: 'NSE', category: 'Pharma', lotSize: 125 },

  // E
  { symbol: 'EICHERMOT', name: 'Eicher Motors Ltd', exchange: 'NSE', category: 'Auto', lotSize: 175 },
  { symbol: 'ESCORTS', name: 'Escorts Kubota Ltd', exchange: 'NSE', category: 'Auto', lotSize: 275 },
  { symbol: 'EXIDEIND', name: 'Exide Industries Ltd', exchange: 'NSE', category: 'Auto', lotSize: 1800 },

  // F
  { symbol: 'FEDERALBNK', name: 'Federal Bank Ltd', exchange: 'NSE', category: 'Banking', lotSize: 5000 },

  // G
  { symbol: 'GAIL', name: 'GAIL (India) Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 2675 },
  { symbol: 'GLENMARK', name: 'Glenmark Pharmaceuticals', exchange: 'NSE', category: 'Pharma', lotSize: 725 },
  { symbol: 'GMRAIRPORT', name: 'GMR Airports Infrastructure', exchange: 'NSE', category: 'Infrastructure', lotSize: 11250 },
  { symbol: 'GNFC', name: 'Gujarat Narmada Valley Fert', exchange: 'NSE', category: 'Chemicals', lotSize: 1300 },
  { symbol: 'GODREJCP', name: 'Godrej Consumer Products', exchange: 'NSE', category: 'FMCG', lotSize: 500 },
  { symbol: 'GODREJPROP', name: 'Godrej Properties Ltd', exchange: 'NSE', category: 'Real Estate', lotSize: 475 },
  { symbol: 'GRANULES', name: 'Granules India Ltd', exchange: 'NSE', category: 'Pharma', lotSize: 2000 },
  { symbol: 'GRASIM', name: 'Grasim Industries Ltd', exchange: 'NSE', category: 'Construction', lotSize: 250 },
  { symbol: 'GUJGASLTD', name: 'Gujarat Gas Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 1250 },

  // H
  { symbol: 'HAL', name: 'Hindustan Aeronautics Ltd', exchange: 'NSE', category: 'Defence', lotSize: 300 },
  { symbol: 'HAVELLS', name: 'Havells India Ltd', exchange: 'NSE', category: 'Consumer Goods', lotSize: 500 },
  { symbol: 'HCLTECH', name: 'HCL Technologies Ltd', exchange: 'NSE', category: 'IT', lotSize: 350 },
  { symbol: 'HDFCBANK', name: 'HDFC Bank Ltd', exchange: 'NSE', category: 'Banking', lotSize: 550 },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance Co', exchange: 'NSE', category: 'Banking', lotSize: 1100 },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp Ltd', exchange: 'NSE', category: 'Auto', lotSize: 150 },
  { symbol: 'HINDALCO', name: 'Hindalco Industries Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 1400 },
  { symbol: 'HINDPETRO', name: 'Hindustan Petroleum Corp', exchange: 'NSE', category: 'Energy & Metals', lotSize: 2700 },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever Ltd', exchange: 'NSE', category: 'FMCG', lotSize: 300 },
  { symbol: 'ICICIBANK', name: 'ICICI Bank Ltd', exchange: 'NSE', category: 'Banking', lotSize: 700 },
  { symbol: 'ICICIGI', name: 'ICICI Lombard General Ins', exchange: 'NSE', category: 'Banking', lotSize: 500 },
  { symbol: 'ICICIPRULI', name: 'ICICI Prudential Life Ins', exchange: 'NSE', category: 'Banking', lotSize: 1500 },
  { symbol: 'IDEA', name: 'Vodafone Idea Ltd', exchange: 'NSE', category: 'Telecommunication', lotSize: 80000 },
  { symbol: 'IDFCFIRSTB', name: 'IDFC First Bank Ltd', exchange: 'NSE', category: 'Banking', lotSize: 7500 },
  { symbol: 'IEX', name: 'Indian Energy Exchange Ltd', exchange: 'NSE', category: 'Capital Goods', lotSize: 3750 },
  { symbol: 'IGL', name: 'Indraprastha Gas Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 1375 },
  { symbol: 'INDHOTEL', name: 'Indian Hotels Co Ltd', exchange: 'NSE', category: 'Consumer Goods', lotSize: 2000 },
  { symbol: 'INDIAMART', name: 'IndiaMART InterMESH Ltd', exchange: 'NSE', category: 'IT', lotSize: 300 },
  { symbol: 'INDIGO', name: 'InterGlobe Aviation Ltd', exchange: 'NSE', category: 'Infrastructure', lotSize: 300 },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank Ltd', exchange: 'NSE', category: 'Banking', lotSize: 500 },
  { symbol: 'INDUSTOWER', name: 'Indus Towers Ltd', exchange: 'NSE', category: 'Telecommunication', lotSize: 3400 },
  { symbol: 'INFY', name: 'Infosys Ltd', exchange: 'NSE', category: 'IT', lotSize: 400 },
  { symbol: 'IOC', name: 'Indian Oil Corp Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 4875 },
  { symbol: 'IPCALAB', name: 'Ipca Laboratories Ltd', exchange: 'NSE', category: 'Pharma', lotSize: 650 },
  { symbol: 'IRCTC', name: 'IRCTC Ltd', exchange: 'NSE', category: 'Infrastructure', lotSize: 875 },
  { symbol: 'ITC', name: 'ITC Ltd', exchange: 'NSE', category: 'FMCG', lotSize: 1600 },

  // J
  { symbol: 'JINDALSTEL', name: 'Jindal Steel & Power Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 625 },
  { symbol: 'JKCEMENT', name: 'JK Cement Ltd', exchange: 'NSE', category: 'Construction', lotSize: 250 },
  { symbol: 'JSWSTEEL', name: 'JSW Steel Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 675 },
  { symbol: 'JUBLFOOD', name: 'Jubilant FoodWorks Ltd', exchange: 'NSE', category: 'FMCG', lotSize: 1250 },

  // K
  { symbol: 'KALYANKJIL', name: 'Kalyan Jewellers India', exchange: 'NSE', category: 'Consumer Goods', lotSize: 1500 },
  { symbol: 'KEI', name: 'KEI Industries Ltd', exchange: 'NSE', category: 'Capital Goods', lotSize: 150 },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd', exchange: 'NSE', category: 'Banking', lotSize: 400 },
  { symbol: 'KPITTECH', name: 'KPIT Technologies Ltd', exchange: 'NSE', category: 'IT', lotSize: 400 },

  // L
  { symbol: 'L&TFH', name: 'L&T Finance Holdings Ltd', exchange: 'NSE', category: 'Banking', lotSize: 4476 },
  { symbol: 'LT', name: 'Larsen & Toubro Ltd', exchange: 'NSE', category: 'Capital Goods', lotSize: 300 },
  { symbol: 'LTM', name: 'LTIMindtree Ltd (LTM)', exchange: 'NSE', category: 'IT', lotSize: 150 },
  { symbol: 'LTTS', name: 'L&T Technology Services', exchange: 'NSE', category: 'IT', lotSize: 200 },
  { symbol: 'LUPIN', name: 'Lupin Ltd', exchange: 'NSE', category: 'Pharma', lotSize: 425 },

  // M
  { symbol: 'M&M', name: 'Mahindra & Mahindra Ltd', exchange: 'NSE', category: 'Auto', lotSize: 350 },
  { symbol: 'M&MFIN', name: 'Mahindra & Mahindra Fin', exchange: 'NSE', category: 'Banking', lotSize: 2000 },
  { symbol: 'MANAPPURAM', name: 'Manappuram Finance Ltd', exchange: 'NSE', category: 'Banking', lotSize: 3000 },
  { symbol: 'MARICO', name: 'Marico Ltd', exchange: 'NSE', category: 'FMCG', lotSize: 1200 },
  { symbol: 'MARUTI', name: 'Maruti Suzuki India Ltd', exchange: 'NSE', category: 'Auto', lotSize: 100 },
  { symbol: 'MCDOWELL-N', name: 'United Spirits Ltd', exchange: 'NSE', category: 'FMCG', lotSize: 700 },
  { symbol: 'MCX', name: 'Multi Commodity Exchange', exchange: 'NSE', category: 'Capital Goods', lotSize: 250 },
  { symbol: 'METROPOLIS', name: 'Metropolis Healthcare Ltd', exchange: 'NSE', category: 'Pharma', lotSize: 300 },
  { symbol: 'MFSL', name: 'Max Financial Services', exchange: 'NSE', category: 'Banking', lotSize: 800 },
  { symbol: 'MGL', name: 'Mahanagar Gas Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 400 },
  { symbol: 'MOTHERSON', name: 'Samvardhana Motherson Int', exchange: 'NSE', category: 'Auto', lotSize: 6150 },
  { symbol: 'MPHASIS', name: 'Mphasis Ltd', exchange: 'NSE', category: 'IT', lotSize: 275 },
  { symbol: 'MRF', name: 'MRF Ltd', exchange: 'NSE', category: 'Auto', lotSize: 5 },
  { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance Ltd', exchange: 'NSE', category: 'Banking', lotSize: 550 },

  // N
  { symbol: 'NATIONALUM', name: 'National Aluminium Co', exchange: 'NSE', category: 'Energy & Metals', lotSize: 3750 },
  { symbol: 'NAVINFLUOR', name: 'Navin Fluorine Intl Ltd', exchange: 'NSE', category: 'Chemicals', lotSize: 175 },
  { symbol: 'NESTLEIND', name: 'Nestle India Ltd', exchange: 'NSE', category: 'FMCG', lotSize: 250 },
  { symbol: 'NMDC', name: 'NMDC Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 4500 },
  { symbol: 'NTPC', name: 'NTPC Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 2250 },

  // O
  { symbol: 'OBEROIRLTY', name: 'Oberoi Realty Ltd', exchange: 'NSE', category: 'Real Estate', lotSize: 700 },
  { symbol: 'OFSS', name: 'Oracle Financial Services', exchange: 'NSE', category: 'IT', lotSize: 100 },
  { symbol: 'OIL', name: 'Oil India Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 1600 },
  { symbol: 'ONGC', name: 'Oil & Natural Gas Corp', exchange: 'NSE', category: 'Energy & Metals', lotSize: 3850 },

  // P
  { symbol: 'PAGEIND', name: 'Page Industries Ltd', exchange: 'NSE', category: 'Consumer Goods', lotSize: 15 },
  { symbol: 'PERSISTENT', name: 'Persistent Systems Ltd', exchange: 'NSE', category: 'IT', lotSize: 100 },
  { symbol: 'PETRONET', name: 'Petronet LNG Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 3000 },
  { symbol: 'PFC', name: 'Power Finance Corp Ltd', exchange: 'NSE', category: 'Banking', lotSize: 1900 },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries Ltd', exchange: 'NSE', category: 'Chemicals', lotSize: 250 },
  { symbol: 'PIIND', name: 'PI Industries Ltd', exchange: 'NSE', category: 'Chemicals', lotSize: 250 },
  { symbol: 'PNB', name: 'Punjab National Bank', exchange: 'NSE', category: 'Banking', lotSize: 8000 },
  { symbol: 'POLYCAB', name: 'Polycab India Ltd', exchange: 'NSE', category: 'Capital Goods', lotSize: 125 },
  { symbol: 'POWERGRID', name: 'Power Grid Corp of India', exchange: 'NSE', category: 'Energy & Metals', lotSize: 2700 },
  { symbol: 'PVRINOX', name: 'PVR INOX Ltd', exchange: 'NSE', category: 'Consumer Goods', lotSize: 407 },

  // R
  { symbol: 'RAMCOCEM', name: 'Ramco Cements Ltd', exchange: 'NSE', category: 'Construction', lotSize: 850 },
  { symbol: 'RBLBANK', name: 'RBL Bank Ltd', exchange: 'NSE', category: 'Banking', lotSize: 2500 },
  { symbol: 'RECLTD', name: 'REC Ltd', exchange: 'NSE', category: 'Banking', lotSize: 1500 },
  { symbol: 'RELIANCE', name: 'Reliance Industries Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 250 },

  // S
  { symbol: 'SAIL', name: 'Steel Authority of India', exchange: 'NSE', category: 'Energy & Metals', lotSize: 8000 },
  { symbol: 'SBICARD', name: 'SBI Cards & Payment Serv', exchange: 'NSE', category: 'Banking', lotSize: 800 },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance Co', exchange: 'NSE', category: 'Banking', lotSize: 375 },
  { symbol: 'SBIN', name: 'State Bank of India', exchange: 'NSE', category: 'Banking', lotSize: 750 },
  { symbol: 'SHREECEM', name: 'Shree Cement Ltd', exchange: 'NSE', category: 'Construction', lotSize: 25 },
  { symbol: 'SHRIRAMFIN', name: 'Shriram Finance Ltd', exchange: 'NSE', category: 'Banking', lotSize: 300 },
  { symbol: 'SIEMENS', name: 'Siemens Ltd', exchange: 'NSE', category: 'Capital Goods', lotSize: 150 },
  { symbol: 'SRF', name: 'SRF Ltd', exchange: 'NSE', category: 'Chemicals', lotSize: 375 },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical Ind', exchange: 'NSE', category: 'Pharma', lotSize: 350 },
  { symbol: 'SUNTV', name: 'Sun TV Network Ltd', exchange: 'NSE', category: 'Media', lotSize: 1500 },
  { symbol: 'SYNGENE', name: 'Syngene International Ltd', exchange: 'NSE', category: 'Pharma', lotSize: 1000 },

  // T
  { symbol: 'TATACOMM', name: 'Tata Communications Ltd', exchange: 'NSE', category: 'Telecommunication', lotSize: 500 },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products', exchange: 'NSE', category: 'FMCG', lotSize: 900 },
  { symbol: 'TATAMOTORS', name: 'Tata Motors Ltd', exchange: 'NSE', category: 'Auto', lotSize: 550 },
  { symbol: 'TATAPOWER', name: 'Tata Power Co Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 1687 },
  { symbol: 'TATASTEEL', name: 'Tata Steel Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 5500 },
  { symbol: 'TCS', name: 'Tata Consultancy Services', exchange: 'NSE', category: 'IT', lotSize: 175 },
  { symbol: 'TECHM', name: 'Tech Mahindra Ltd', exchange: 'NSE', category: 'IT', lotSize: 600 },
  { symbol: 'TITAN', name: 'Titan Company Ltd', exchange: 'NSE', category: 'Consumer Goods', lotSize: 175 },
  { symbol: 'TORNTPHARM', name: 'Torrent Pharmaceuticals', exchange: 'NSE', category: 'Pharma', lotSize: 250 },
  { symbol: 'TORNTPOWER', name: 'Torrent Power Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 750 },
  { symbol: 'TRENT', name: 'Trent Ltd', exchange: 'NSE', category: 'Consumer Goods', lotSize: 100 },
  { symbol: 'TVSMOTOR', name: 'TVS Motor Co Ltd', exchange: 'NSE', category: 'Auto', lotSize: 350 },

  // U
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement Ltd', exchange: 'NSE', category: 'Construction', lotSize: 100 },
  { symbol: 'UPL', name: 'UPL Ltd', exchange: 'NSE', category: 'Chemicals', lotSize: 1300 },

  // V
  { symbol: 'VBL', name: 'Varun Beverages Ltd', exchange: 'NSE', category: 'FMCG', lotSize: 750 },
  { symbol: 'VEDL', name: 'Vedanta Ltd', exchange: 'NSE', category: 'Energy & Metals', lotSize: 2300 },
  { symbol: 'VOLTAS', name: 'Voltas Ltd', exchange: 'NSE', category: 'Consumer Goods', lotSize: 600 },

  // W
  { symbol: 'WIPRO', name: 'Wipro Ltd', exchange: 'NSE', category: 'IT', lotSize: 1500 },

  // Z
  { symbol: 'ZEEL', name: 'Zee Entertainment Ent', exchange: 'NSE', category: 'Media', lotSize: 3000 },
  { symbol: 'ZYDUSLIFE', name: 'Zydus Lifesciences Ltd', exchange: 'NSE', category: 'Pharma', lotSize: 900 },
];
